apiVersion: 1

datasources:
  - name: InfluxDB
    uid: influxdb
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: engine-org
      defaultBucket: telemetry
    secureJsonData:
      token: my-token
    isDefault: true
